on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub's repository
        uses: actions/checkout@v3
      - name: Create new tag
        run: make release
      - name: Publish package
        run: make publish
      - name: Send notification
        run: make notify

